firstproj/firstproj/urls.py
from django.contrib import admin
from django.urls import path,include
from newsadmin import views as nviews

from sunapp.views import hello,hello1,hello2,student
from students.views import listone,listall
from students.views import post,post1,postform
from students.views import delete,edit
from CookieSessionApp import views as csviews
from flower import views as fviews
from django.conf import settings 
from django.conf.urls.static import static

from boardapp import views as bviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',hello),
    path('hello1/<str:username>',hello1),
    path('hello2/<str:username>',hello2),
    path('stds/',student),
    path('listone/',listone),
    path('listall/',listall),
    path('post/',post),
    path('post1/',post1),
    path('postform/',postform),
    path('delete/<str:stdId>/',delete),
    path('edit/<str:stdId>/<str:mode>/',edit),
    path('edit/<str:stdId>/',edit),

    # cookies
    path('set_cookie/<str:key>/<str:value>/', csviews.set_cookie),
	path('set_cookie2/<str:key>/<str:value>/', csviews.set_cookie2),
	path('get_cookie/<str:key>/', csviews.get_cookie),
	path('get_allcookies/', csviews.get_allcookies),
	path('delete_cookie/<str:key>/', csviews.delete_cookie),
    path('pagecount/', csviews.pagecount),
    # sessions
    path('set_session/<str:key>/<str:value>/', csviews.set_session),
	path('get_session/<str:key>/', csviews.get_session),
	path('get_allsessions/', csviews.get_allsessions),
	# vote
	path('vote/', csviews.vote),	
	path('set_session2/<str:key>/<str:value>/', csviews.set_session2),
	path('delete_session/<str:key>/', csviews.delete_session),
    # login
	path('login/', csviews.login),	
	path('logout/', csviews.logout),


    path('mypage/',csviews.mypage),
    path('adduser/',csviews.adduser),
    path('register/',csviews.register),
 	

	path('newsindex/', nviews.index),
	path('newsindex/<str:pageindex>/', nviews.index),
	path('newsdetail/<int:detailid>/', nviews.detail),
	path('newslogin/', nviews.login),
	path('newslogout/', nviews.logout),

	path('newsadminmain/', nviews.adminmain),
	path('newsadminmain/<str:pageindex>/', nviews.adminmain),

    path('newsadd/', nviews.newsadd),
	path('newsedit/<int:newsid>/', nviews.newsedit),
	path('newsedit/<int:newsid>/<str:edittype>/', nviews.newsedit),
	path('newsdelete/<int:newsid>/', nviews.newsdelete),
	path('newsdelete/<int:newsid>/<str:deletetype>/', nviews.newsdelete),
    
    path('accounts/', include('allauth.urls')),

    path('showpost/', bviews.showpost),
    path('addpost/', bviews.addpost),
    path('captcha/', include('captcha.urls')),

    path('flower/', fviews.flowers),
    path('flower/create/', fviews.create, name='create'),
    path('flower/edit/<int:pk>/', fviews.edit, name='edit'),
    path('flower/delete/<int:pk>/', fviews.delete, name='delete'),
    path('flower/<slug:slug>/', fviews.detail, name='detail'),


    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

firstproj/flower/models.py
from django.db import models
from django.utils.text import slugify 
from django.urls import reverse
# Create your models here.

# 定義分類名稱欄位
class Category(models.Model):

    title = models.CharField(max_length=255, default="")

    def __str__(self):

        return self.title

# 定義標籤名稱欄位   
class Tag(models.Model):
    title = models.CharField(max_length=255, default="")

    def __str__(self):
        return self.title
    
# 定義商品資料欄位    
class Flower(models.Model):

    title = models.CharField(max_length=255, default="")

    description = models.TextField(default="")

    slug = models.SlugField(blank=True, default="") 
    category = models.ForeignKey(Category, null=True, on_delete=models.PROTECT) 
    tags = models.ManyToManyField(Tag)
    image = models.ImageField(default="", blank=True, upload_to="images")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title) 
        super(Flower, self).save()

    def get_absolute_url(self):
        return reverse("detail", args=[str(self.slug)])

firstproj/flower/forms.py
from django import forms
from django.forms import ModelForm
from .models import Flower

class FlowerForm(ModelForm):
    title = forms.CharField(label='Title',widget= forms.TextInput(attrs={'class': 'form-control '}))
    class Meta:
        model = Flower
        #fields = ['title']
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'tags': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'image': forms.FileInput(attrs={'class': 'form-control', 'id': 'image_field'})
        }
        labels = {
            'title': '名稱',
            'description': '敘述',
            'slug': '代號',
            'category': '類別',
            'tags': '標籤',
            'image': '圖片'
        }

firstproj/flower/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404,HttpResponseRedirect
from flower.models import Flower
from .forms import FlowerForm
# Create your views here.

def flowers(request):
    q = request.GET.get('q', None)
    flowers = '' 
    if q is None or q is "":
        flowers = Flower.objects.all() 
    elif q is not None:
        flowers = Flower.objects.filter(title__contains=q)
    return render(request, 'flower/flower.html', {'flowers': flowers })

def detail(request, slug=None):
    flower = get_object_or_404(Flower, slug=slug)
    return render(request, 'flower/detail.html', locals())

def create(request):
    if request.method == 'POST':
        form = FlowerForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/flower/')
    else:
        form = FlowerForm()
    return render(request, 'flower/edit.html', {'form': form})

def edit(request, pk=None):
    flower = get_object_or_404(Flower, pk=pk)
    if request.method == "POST":
        form = FlowerForm(request.POST, instance=flower)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('flower/')
    else:
        form = FlowerForm(instance=flower)

    return render(request, 'flower/edit.html', {'form': form})

def delete(request, pk=None):
    flower = get_object_or_404(Flower, pk=pk)
    flower.delete()
    return render(request, 'flower/')

firstproj/templates/flower/detail.html
{% extends "base.html" %}
{% block title %}顯示花朵資料{% endblock %}
{% block content %}
<br>
<br>
<br>
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-3">{{ flower.title }}</h1>
            <div class="lead">{{ flower.description }}</div>
        </div>
    </div>
    <a href="/flower/">Back</a>
{% endblock %}

firstproj/templates/flower/edit.html
{% extends "base.html" %}
{% block title %}編輯花朵資料{% endblock %}
{% block content %}
<br>
<br>
<br>
    <form action="" method="post">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-6">
            {{ form }}
            <hr class="mb-3">
            <button class="btn btn-primary btn-lg btn-block" type="submit">Submit</button>
            </div>
        </div>
    </form>
{% endblock %}

firstproj/templates/flower/flower.html
{% extends "base.html" %}
{% block title %}顯示花朵資料{% endblock %}
{% block content %}
<br>
<br>
<br>
    <div class="card-columns">
    {% for flower in flowers %}
    <div class="card">
        <div class="card-body">
 
            <h5 class="card-title"><a href="{% url 'detail' flower.slug %}">{{ flower.title }}</a></h5>
            <img class="card-img-top" src="{{ flower.image.url }}" alt="Card image cap">
            <p class="card-text">{{ flower.description | truncatechars:100 }}</p>
            <a href="#" class="card-link">{{ flower.category }}</a>
            <!--<a href="/admin/flower/flower/{{ flower.id }}/change/" class="card-link">Edit</a> -->
            <!--<a href="/admin/flower/flower/{{ flower.id }}/delete/" class="card-link">Delete</a>-->

            <a href="{% url 'edit' pk=flower.pk %}" class="card-link">Edit</a>
            <a href="{% url 'delete' pk=flower.pk %}" class="card-link">Delete</a>
            <hr>
 
            All flowers in the <strong>{{ flower.category }}</strong> category:<br>
            {% for c_flower in flower.category.flower_set.all %}
                <a href="#" class="card-link">{{ c_flower }}</a><br>
            {% endfor %}
        </div>
    </div>
{% endfor %}
    </div>
{% endblock %}